SEVERE :: Thu Apr 30 11:34:30 EET 2020 :: Ops error appeared on addon-create: Field error in object 'addonDto' on field 'name': rejected value []; codes [NotBlank.addonDto.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [addonDto.name,name]; arguments []; default message [name]]; default message [must not be blank]
